google_sheets:
  credentials_file: "credentials.json"
  token_file: "token.pickle"
  scopes:
    - "https://www.googleapis.com/auth/spreadsheets"
    - "https://www.googleapis.com/auth/drive.readonly"
  spreadsheet_id: null  # Optional: can be provided via CLI

languages:
  source: "en"                # Source language code
  target: ["es", "fr", "de"]  # Default target languages if not specified via CLI

translation:
  # Convert space before interpunction to non-breaking space (default: true)
  # Useful for e.g. French language, where most interpunction marks have to be preceeded by a space,
  # so that the word before interpunction is joined with the interpunction mark and displayed as a single word.
  convert_space_before_interpunction_to_nbsp: true

  # Non-Breaking Space Before Interpunction Mode of operation ('unicode', 'html', 'nobr', 'space')
  # 'unicode': Replace space with unicode non-breaking space
  # 'html': Replace space with <nbsp> HTML tag
  # 'nobr': Wrap space and interpunction with <nobr></nobr> tag
  # 'space': Use regular space (no transformation)
  space_to_nbsp_mode: "nobr"

llm:
  api_key: ""  # Set via LLM_API_KEY environment variable
  model: "anthropic/claude-3-5-sonnet-20241022"    # The LLM model to use (e.g., "gpt-4", "claude-3-5-sonnet-20241022")
  batch_size: 25    # Number of rows to process in a single batch (recommended: 5-20)
  
  additional_llm_context: "Additional context and instructions for the LLM, like app name and description, company name, etc."

  temperature: 0.2  # Controls randomness in responses (0.0-1.0)
  max_retries: 5    # Maximum retry attempts
  retry_delay: 1    # Initial delay between retries in seconds

qa:
  max_length: 1000  # Maximum length for translations
  capitalization_check: true  # Check for capitalization mismatch between source and translation
  newline_check: true  # Check for newline count mismatch between source and translation
  ending_punctuation_check: true  # Check for ending punctuation mismatch between source and translation
  remove_html_tags_before_validation: true  # Remove HTML tags before validation
  non_translatable_patterns:  # Terms that must appear exactly the same in translations
    - start: "{["   # Example: {[NUMBER]} must appear exactly as {[NUMBER]} in translation
      end: "]}"
    - start: "<"    # Example: <variable> must appear exactly as <variable> in translation
      end: ">"
    - start: "["    # Example: [TERM] must appear exactly as [TERM] in translation
      end: "]"

context_columns:
  patterns:
    - "comment"     # Will match: comment, comments, commented, etc.
    - "description" # Will match: description, descriptions, etc.
    - "context"     # Will match: context, contextual, etc.
    - "note"        # Will match: note, notes, notation, etc.
    - "info"        # Will match: info, information, etc.
  ignore_case: true  # Will match regardless of case

term_base:
  add_terms_to_term_base: true  # Add suggested terms to term base
  sheet_name: "term_base"  # Name of the sheet containing term base

ui:
  type: graphical  # Use graphical output mode

output:
  dir: "translation_logs"  # Directory for storing translation logs and reports
